### ISSUE TITLE
Fix error handling in SDK Client

### ISSUE THREAD

**Issue by rafalcymerys** [spree/spree-storefront-api-v2-js-sdk#342]
Spree errors are not parsed properly - when getting any bad request(404 etc.) errors are parsed to Error type and not FetchError which should be then parsed once more to a proper Spree error. Some other modules that use SDK may not work properly since the format changed. We should fix it to prevent any further issues.

**Comment by rafalkosla101** [comment]
Spree errors are not parsed properly - when getting any bad request(404 etc.) errors are parsed to Error type and not FetchError which should be then parsed once more to a proper Spree error. Some other modules that use  SDK may not work properly since the format changed. We should fix it to prevent any further issues.
